import numpy as np
import matplotlib.pyplot as plt

class System:
    def __init__(self, num_particles, x, v, m, G):
        self.num_particles = num_particles
        self.x = x
        self.v = v
        self.m = m
        self.G = G
    
    def com_correction(self):
        """
        Shift the system so that the center of mass (CoM) is at the origin and the net velocity of 
        the system is zero.
        
        This prevents the whole system from drifting in space
        due to numerical or initial condition offsets.
        """        

        x_cm = np.zeros(3)            
        v_cm = np.zeros(3)
        M = 0.0

        for i in range(self.num_particles):
            x_cm += self.m[i] * self.x[i]
            v_cm += self.m[i] * self.v[i]
            M += self.m[i]
        
        x_cm /= M
        v_cm /= M

        self.x -= x_cm
        self.v -= v_cm

def get_initial_conditions(initial_condition):
    """
    Returns the initial conditions for solar system,
    with units AU, days, and M_sun.
    """

    # Conversion factor from km^3 s^-2 to AU^3 d^-2
    CONVERSION_FACTOR = (86400**2) / (149597870.7**3)

    # GM values (km^3 s^-2)
    # ref: https://ssd.jpl.nasa.gov/doc/Park.2021.AJ.DE440.pdf
    GM_KM_S = {
        "Sun": 132712440041.279419,
        "Mercury": 22031.868551,
        "Venus": 324858.592000,
        "Earth": 398600.435507,
        "Mars": 42828.375816,
        "Jupiter": 126712764.100000,
        "Saturn": 37940584.841800,
        "Uranus": 5794556.400000,
        "Neptune": 6836527.100580,
        "Moon": 4902.800118,
        "Pluto": 975.500000,
        "Ceres": 62.62890,
        "Vesta": 17.288245,
    }

    # Gravitational constant in AU^3 d^-2
    G = GM_KM_S["Sun"] * CONVERSION_FACTOR

    # Solar system masses (M_sun^-1)
    SOLAR_SYSTEM_MASSES = {
        body: GM_KM_S[body] / GM_KM_S["Sun"] for body in GM_KM_S
    }

    # Solar system position and velocities data
    # Units: AU-D
    # Coordinate center: Solar System Barycenter
    # Data dated on A.D. 2024-Jan-01 00:00:00.0000 TDB
    # Computational data generated by NASA JPL Horizons System https://ssd.jpl.nasa.gov/horizons/
    SOLAR_SYSTEM_POS = {
        "Sun": [-7.967955691533730e-03, -2.906227441573178e-03, 2.103054301547123e-04],
        "Mercury": [-2.825983269538632e-01, 1.974559795958082e-01, 4.177433558063677e-02],
        "Venus": [-7.232103701666379e-01, -7.948302026312400e-02, 4.042871428174315e-02],
        "Earth": [-1.738192017257054e-01, 9.663245550235138e-01, 1.553901854897183e-04],
        "Mars": [-3.013262392582653e-01, -1.454029331393295e00, -2.300531433991428e-02],
        "Jupiter": [3.485202469657674e00, 3.552136904413157e00, -9.271035442798399e-02],
        "Saturn": [8.988104223143450e00, -3.719064854634689e00, -2.931937777323593e-01],
        "Uranus": [1.226302417897505e01, 1.529738792480545e01, -1.020549026883563e-01],
        "Neptune": [2.983501460984741e01, -1.793812957956852e00, -6.506401132254588e-01],
        "Moon": [-1.762788124769829e-01, 9.674377513177153e-01, 3.236901585768862e-04],
        "Pluto": [1.720200478843485e01, -3.034155683573043e01, -1.729127607100611e00],
        "Ceres": [-1.103880510367569e00, -2.533340440444230e00, 1.220283937721780e-01],
        "Vesta": [-8.092549658731499e-02, 2.558381434460076e00, -6.695836142398572e-02],
    }

    SOLAR_SYSTEM_VEL = {
        "Sun": [4.875094764261564e-06, -7.057133213976680e-06, -4.573453713094512e-08],
        "Mercury": [-2.232165900189702e-02, -2.157207103176252e-02, 2.855193410495743e-04],
        "Venus": [2.034068201002341e-03, -2.020828626592994e-02, -3.945639843855159e-04],
        "Earth": [-1.723001232538228e-02, -2.967721342618870e-03, 6.382125383116755e-07],
        "Mars": [1.424832259345280e-02, -1.579236181580905e-03, -3.823722796161561e-04],
        "Jupiter": [-5.470970658852281e-03, 5.642487338479145e-03, 9.896190602066252e-05],
        "Saturn": [1.822013845554067e-03, 5.143470425888054e-03, -1.617235904887937e-04],
        "Uranus": [-3.097615358317413e-03, 2.276781932345769e-03, 4.860433222241686e-05],
        "Neptune": [1.676536611817232e-04, 3.152098732861913e-03, -6.877501095688201e-05],
        "Moon": [-1.746667306153906e-02, -3.473438277358121e-03, -3.359028758606074e-05],
        "Pluto": [2.802810313667557e-03, 8.492056438614633e-04, -9.060790113327894e-04],
        "Ceres": [8.978653480111301e-03, -4.873256528198994e-03, -1.807162046049230e-03],
        "Vesta": [-1.017876585480054e-02, -5.452367109338154e-04, 1.255870551153315e-03],
    }

    SOLAR_SYSTEM_COLORS = {
        "Sun": "orange",
        "Mercury": "slategrey",
        "Venus": "wheat",
        "Earth": "skyblue",
        "Mars": "red",
        "Jupiter": "darkgoldenrod",
        "Saturn": "gold",
        "Uranus": "paleturquoise",
        "Neptune": "blue",
        "Pluto": None,
        "Ceres": None,
        "Vesta": None,
    }

    def build_system(names):
        x = np.array([SOLAR_SYSTEM_POS[n] for n in names])
        v = np.array([SOLAR_SYSTEM_VEL[n] for n in names])
        m = np.array([SOLAR_SYSTEM_MASSES[n] for n in names])

        system = System(
            num_particles=len(names),
            x=x,
            v=v,
            m=m,
            G=G,
        )
        system.com_correction()

        labels = names
        colors = [SOLAR_SYSTEM_COLORS.get(n) for n in names]

        return system, labels, colors, True

    if initial_condition == "pyth-3-body":
        x = np.array([[1.0, 3.0, 0.0], [-2.0, -1.0, 0.0], [1.0, -1.0, 0.0]])
        v = np.zeros_like(x)
        m = np.array([3.0, 4.0, 5.0]) / G

        system = System(
            num_particles=3,
            x=x,
            v=v,
            m=m,
            G=G,
        )
        system.com_correction()

        return system, [None, None, None], [None, None, None], False

    elif initial_condition == "solar_system":
        names = ["Sun", "Mercury", "Venus", "Earth", "Mars",
                 "Jupiter", "Saturn", "Uranus", "Neptune"]
        return build_system(names)

    elif initial_condition == "solar_system_plus":
        names = ["Sun", "Mercury", "Venus", "Earth", "Mars",
                 "Jupiter", "Saturn", "Uranus", "Neptune",
                 "Pluto", "Ceres", "Vesta"]
        return build_system(names)

    else:
        raise ValueError(f"Initial condition not recognized: {initial_condition}")
    
def plot_initial_conditions(system, labels, colors, legend):
    fig, ax = plt.subplots()

    ax.set_xlabel("$x$ (AU)")
    ax.set_ylabel("$y$ (AU)")

    for i in range(system.num_particles):
        ax.scatter(system.x[i, 0], system.x[i, 1], marker="o", color=colors[i], label=labels[i])

    if legend:
        ax.legend()
    
    plt.show()

def acceleration(a, system):
    """
    Computing the gravitational acceleration using Newton's law of gravitation
    """
    a.fill(0.0)

    x = system.x
    m = system.m
    G = system.G
    N = system.num_particles

    for i in range(N):
        for j in range(i + 1, N):
            r = x[j] - x[i]
            dist = np.linalg.norm(r)

            factor = G / dist ** 3

            a[i] += factor * m[j] * r
            a[j] -= factor * m[i] * r
